"""autogenerated by genpy from joint_movement/Pose.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Pose(genpy.Message):
  _md5sum = "7c7c43e96731a35482506ec2cf4a77aa"
  _type = "joint_movement/Pose"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 x
float64 y
float64 z
float64 u
float64 v
float64 w
float64 a
float64 i
float64 j
float64 k

"""
  __slots__ = ['x','y','z','u','v','w','a','i','j','k']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,u,v,w,a,i,j,k

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Pose, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.u is None:
        self.u = 0.
      if self.v is None:
        self.v = 0.
      if self.w is None:
        self.w = 0.
      if self.a is None:
        self.a = 0.
      if self.i is None:
        self.i = 0.
      if self.j is None:
        self.j = 0.
      if self.k is None:
        self.k = 0.
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.u = 0.
      self.v = 0.
      self.w = 0.
      self.a = 0.
      self.i = 0.
      self.j = 0.
      self.k = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_10d.pack(_x.x, _x.y, _x.z, _x.u, _x.v, _x.w, _x.a, _x.i, _x.j, _x.k))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 80
      (_x.x, _x.y, _x.z, _x.u, _x.v, _x.w, _x.a, _x.i, _x.j, _x.k,) = _struct_10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_10d.pack(_x.x, _x.y, _x.z, _x.u, _x.v, _x.w, _x.a, _x.i, _x.j, _x.k))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 80
      (_x.x, _x.y, _x.z, _x.u, _x.v, _x.w, _x.a, _x.i, _x.j, _x.k,) = _struct_10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_10d = struct.Struct("<10d")
